package ExceptionDemo;

public class ExceptionDemo1 {

	public static void main(String[] args)
	{
		System.out.println("main method start");
		System.out.println(10/0);  //we will get an exception
		System.out.println("done");
		

	}

}
